/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administracion;

import controlador.consulta;
import entidades.Admision;
import entidades.Antecedentes;
import entidades.Datos_personales;
import entidades.Desempeño;
import entidades.acceso;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RM-PC
 */
public class Admisionagregar extends javax.swing.JFrame {
    consulta con = new consulta();
    /**
     * Creates new form Admisionagregar
     */
    public Admisionagregar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jefeTXT = new javax.swing.JTextField();
        salarioTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contratoTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cargoinicialTXT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        areaTXT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CONTRATO LABORAL:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 180, 30));
        jPanel1.add(jefeTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 180, 40));

        salarioTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioTXTActionPerformed(evt);
            }
        });
        jPanel1.add(salarioTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 180, 40));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SALARIO INICIAL:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 20));
        jPanel1.add(contratoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 180, 40));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CARGO INICIAL:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 20));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FECHA DE CONTRATO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 20));
        jPanel1.add(fechaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 180, 40));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NOMBRE DE JEFE:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, 30));
        jPanel1.add(cargoinicialTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 180, 40));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("AREA ASIGNADA:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 160, 30));
        jPanel1.add(areaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 180, 40));

        jButton1.setText("AGREGAR EMPLEADO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 720, 402));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salarioTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioTXTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String fecha = this.fechaTXT.getText();
       String cargo = this.cargoinicialTXT.getText();
       String salario = this.salarioTXT.getText();
       String jefe = this.jefeTXT.getText();
       String area = this.areaTXT.getText();
       String contrato =  this.contratoTXT.getText();
       
        if(this.fechaTXT.getText().isEmpty() ||this.cargoinicialTXT.getText().isEmpty() || this.salarioTXT.getText().isEmpty() ||
                this.jefeTXT.getText().isEmpty() || this.areaTXT.getText().isEmpty() || this.contratoTXT.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "No dejar campos Vacíos", "Error!", JOptionPane.ERROR_MESSAGE);
            
            
        }else{
            try {
                con.MySQLConnection();
                con.tam();
                con.agregar_admision(fecha, cargo, salario, jefe, area, contrato);
                
                this.setVisible(false);
                login login = new login();
                login.setVisible(true);
                
                
            } catch (Exception ex) {
                Logger.getLogger(Admisionagregar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admisionagregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admisionagregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admisionagregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admisionagregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admisionagregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField areaTXT;
    public javax.swing.JTextField cargoinicialTXT;
    public javax.swing.JTextField contratoTXT;
    public static javax.swing.JTextField fechaTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jefeTXT;
    public javax.swing.JTextField salarioTXT;
    // End of variables declaration//GEN-END:variables
}
