/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administracion;

import static java.lang.Double.parseDouble;
import javax.swing.JOptionPane;

/**
 *
 * @author je_pa
 */
public class Buscar extends javax.swing.JFrame {
    
    MySQL db = new MySQL();
    
    public Buscar() {
        try{
            db.MySQLConnection();
        }
        catch(Exception e){
            
        }
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarBTN = new javax.swing.JButton();
        codigoTXT = new javax.swing.JTextField();
        sexoCB = new javax.swing.JComboBox<>();
        civilCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarBTN.setText("BUSCAR");
        buscarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(buscarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 110, 40));

        codigoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTXTActionPerformed(evt);
            }
        });
        getContentPane().add(codigoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 370, 70));

        sexoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        getContentPane().add(sexoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 140, 50));

        civilCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo", "Acompañado" }));
        getContentPane().add(civilCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTXTActionPerformed

    private void buscarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBTNActionPerformed
        String codigo = codigoTXT.getText();
        String sexo = sexoCB.getSelectedItem().toString();
        String civil = civilCB.getSelectedItem().toString();
        
        String cargo = codigoTXT.getText();
        
        //double nota = parseDouble(codigoTXT.getText());
        //db.buscarEmpleado(codigo);
        //db.buscarSexo(sexo);
        //db.buscarCivil(civil);
        
        
        db.buscarCargo(cargo);
        
        //(JOptionPane.showMessageDialog(null, "EMPLEADO/S ENCONTRADO/S \n" + db.lista , "BUSQUEDA", JOptionPane.INFORMATION_MESSAGE);
        //db.lista.clear();
        JOptionPane.showMessageDialog(null, "EMPLEADO/S ENCONTRADO/S \n" + db.lista , "BUSQUEDA", JOptionPane.INFORMATION_MESSAGE);
        db.lista.clear();
        
    }//GEN-LAST:event_buscarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBTN;
    private javax.swing.JComboBox<String> civilCB;
    private javax.swing.JTextField codigoTXT;
    private javax.swing.JComboBox<String> sexoCB;
    // End of variables declaration//GEN-END:variables
}
