/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administracion;

/**
 *
 * @author RM-PC
 */
public class desempeño extends javax.swing.JPanel {

    /**
     * Creates new form desempeño
     */
    public desempeño() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        notaTXT = new javax.swing.JTextField();
        remuneracionTXT = new javax.swing.JTextField();
        antiguoJefeTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cargoActualTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        habilidadesTXT = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REMUNERACION:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 160, 30));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NOTA ALCANZADA:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 160, -1));

        notaTXT.setEditable(false);
        notaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaTXTActionPerformed(evt);
            }
        });
        add(notaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 270, 40));

        remuneracionTXT.setEditable(false);
        add(remuneracionTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 270, 40));

        antiguoJefeTXT.setEditable(false);
        antiguoJefeTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antiguoJefeTXTActionPerformed(evt);
            }
        });
        add(antiguoJefeTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 270, 40));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FECHA DE LA ULTIMA EVALUACION");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 290, 20));

        cargoActualTXT.setEditable(false);
        add(cargoActualTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 270, 40));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CARGO ACTUALMENTE:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 200, 20));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HABILIDADES TECNICAS Y MANUALES:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 310, 20));

        habilidadesTXT.setEditable(false);
        add(habilidadesTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 270, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void notaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaTXTActionPerformed

    private void antiguoJefeTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antiguoJefeTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antiguoJefeTXTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField antiguoJefeTXT;
    private javax.swing.JTextField cargoActualTXT;
    public static javax.swing.JTextField habilidadesTXT;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField notaTXT;
    private javax.swing.JTextField remuneracionTXT;
    // End of variables declaration//GEN-END:variables
}
