/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administracion;

/**
 *
 * @author RM-PC
 */
public class menu extends javax.swing.JFrame {
    MySQL db = new MySQL();
    
    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosBTN = new javax.swing.JButton();
        antecedentesBTN = new javax.swing.JButton();
        desempeñoBTN = new javax.swing.JButton();
        admisionBTN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosBTN.setBackground(new java.awt.Color(204, 204, 204));
        datosBTN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        datosBTN.setText("DATOS PERSONALES");
        datosBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        datosBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datosBTN.setFocusable(false);
        getContentPane().add(datosBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 180, 70));

        antecedentesBTN.setBackground(new java.awt.Color(204, 204, 204));
        antecedentesBTN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        antecedentesBTN.setText("ANTECEDENTES");
        antecedentesBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        antecedentesBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        antecedentesBTN.setFocusable(false);
        getContentPane().add(antecedentesBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 180, 70));

        desempeñoBTN.setBackground(new java.awt.Color(204, 204, 204));
        desempeñoBTN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        desempeñoBTN.setText("DESEMPEÑO");
        desempeñoBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        desempeñoBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desempeñoBTN.setFocusable(false);
        getContentPane().add(desempeñoBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 180, 70));

        admisionBTN.setBackground(new java.awt.Color(204, 204, 204));
        admisionBTN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        admisionBTN.setText("DATOS DE ADMISION");
        admisionBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        admisionBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admisionBTN.setFocusable(false);
        admisionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admisionBTNActionPerformed(evt);
            }
        });
        getContentPane().add(admisionBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 180, 70));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admisionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admisionBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admisionBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admisionBTN;
    private javax.swing.JButton antecedentesBTN;
    private javax.swing.JButton datosBTN;
    private javax.swing.JButton desempeñoBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
